import { ISection } from "@/types/index";

const sections: ISection[] = [
  // JHS Sections
  {
    id: "1",
    name: "JRHS701A",
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "1",
  },
  {
    id: "2",
    name: "JRHS801A",
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "2",
  },
  {
    id: "3",
    name: "JRHS801B",
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "2",
  },
  {
    id: "4",
    name: "JRHS901A",
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "3",
  },
  {
    id: "5",
    name: "JRHS1001A",
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "4",
  },

  // SHS Sections
  {
    id: "6",
    name: "ABM101A",
    academicLevelId: "2",
    courseId: "3",
    yearLevelId: "1",
  },
  {
    id: "7",
    name: "ABM201A",
    academicLevelId: "2",
    courseId: "3",
    yearLevelId: "2",
  },
  {
    id: "8",
    name: "HUMSS101A",
    academicLevelId: "2",
    courseId: "4",
    yearLevelId: "1",
  },
  {
    id: "9",
    name: "HUMSS101B",
    academicLevelId: "2",
    courseId: "4",
    yearLevelId: "1",
  },
  {
    id: "10",
    name: "HUMSS101B",
    academicLevelId: "2",
    courseId: "4",
    yearLevelId: "1",
  },
  {
    id: "11",
    name: "HUMSS201A",
    academicLevelId: "2",
    courseId: "4",
    yearLevelId: "2",
  },
  {
    id: "12",
    name: "HUMSS201B",
    academicLevelId: "2",
    courseId: "4",
    yearLevelId: "2",
  },
  {
    id: "13",
    name: "ITMAWD101A",
    academicLevelId: "2",
    courseId: "5",
    yearLevelId: "1",
  },
  {
    id: "14",
    name: "ITMAWD201A",
    academicLevelId: "2",
    courseId: "5",
    yearLevelId: "2",
  },
  {
    id: "15",
    name: "STEM101A",
    academicLevelId: "2",
    courseId: "2",
    yearLevelId: "1",
  },
  {
    id: "16",
    name: "STEM101B",
    academicLevelId: "2",
    courseId: "2",
    yearLevelId: "1",
  },
  {
    id: "17",
    name: "STEM101C",
    academicLevelId: "2",
    courseId: "2",
    yearLevelId: "1",
  },
  {
    id: "18",
    name: "STEM201A",
    academicLevelId: "2",
    courseId: "2",
    yearLevelId: "2",
  },
  {
    id: "19",
    name: "STEM201B",
    academicLevelId: "2",
    courseId: "2",
    yearLevelId: "2",
  },
  {
    id: "20",
    name: "STEM201C",
    academicLevelId: "2",
    courseId: "2",
    yearLevelId: "2",
  },
  {
    id: "21",
    name: "STEM201D",
    academicLevelId: "2",
    courseId: "2",
    yearLevelId: "2",
  },

  // TER Sections
  {
    id: "22",
    name: "BSAIS101A",
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "1",
  },
  {
    id: "23",
    name: "BSAIS201A",
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "2",
  },
  {
    id: "24",
    name: "BSAIS301A",
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "3",
  },
  {
    id: "25",
    name: "BSAIS401A",
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "4",
  },
  {
    id: "26",
    name: "BSBA101A",
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "1",
  },
  {
    id: "27",
    name: "BSBA201A",
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "2",
  },
  {
    id: "28",
    name: "BSBA301A",
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "3",
  },
  {
    id: "29",
    name: "BSBA301B",
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "3",
  },
  {
    id: "30",
    name: "BSBA401A",
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "4",
  },
  {
    id: "31",
    name: "BSBA401A",
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "4",
  },
  {
    id: "32",
    name: "BSCPE101A",
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "1",
  },
  {
    id: "33",
    name: "BSCPE201A",
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "2",
  },
  {
    id: "34",
    name: "BSCPE301A",
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "3",
  },
  {
    id: "35",
    name: "BSCPE401A",
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "4",
  },
  {
    id: "36",
    name: "BSHM101A",
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "1",
  },
  {
    id: "37",
    name: "BSHM101B",
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "1",
  },
  {
    id: "38",
    name: "BSHM101C",
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "1",
  },
  {
    id: "39",
    name: "BSHM101D",
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "1",
  },
  {
    id: "40",
    name: "BSHM201A",
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "2",
  },
  {
    id: "41",
    name: "BSHM201B",
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "2",
  },
  {
    id: "42",
    name: "BSHM201C",
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "2",
  },
  {
    id: "43",
    name: "BSHM201D",
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "2",
  },
  {
    id: "44",
    name: "BSHM201E",
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "2",
  },
  {
    id: "45",
    name: "BSHM301A",
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "3",
  },
  {
    id: "46",
    name: "BSHM301B",
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "3",
  },
  {
    id: "47",
    name: "BSHM301C",
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "3",
  },
  {
    id: "48",
    name: "BSHM301D",
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "3",
  },
  {
    id: "49",
    name: "BSHM301E",
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "3",
  },
  {
    id: "50",
    name: "BSHM301F",
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "3",
  },
  {
    id: "51",
    name: "BSHM301G",
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "3",
  },
  {
    id: "52",
    name: "BSHM401A",
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "4",
  },
  {
    id: "53",
    name: "BSHM401B",
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "4",
  },
  {
    id: "54",
    name: "BSHM401C",
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "4",
  },
  {
    id: "55",
    name: "BSIT101A",
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "1",
  },
  {
    id: "56",
    name: "BSIT101B",
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "1",
  },
  {
    id: "57",
    name: "BSIT101C",
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "1",
  },
  {
    id: "58",
    name: "BSIT201A",
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "2",
  },
  {
    id: "59",
    name: "BSIT201B",
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "2",
  },
  {
    id: "60",
    name: "BSIT201C",
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "2",
  },
  {
    id: "61",
    name: "BSIT201D",
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "2",
  },
  {
    id: "62",
    name: "BSIT301A",
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "3",
  },
  {
    id: "63",
    name: "BSIT301B",
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "3",
  },
  {
    id: "64",
    name: "BSIT301C",
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "3",
  },
  {
    id: "65",
    name: "BSIT301D",
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "3",
  },
  {
    id: "66",
    name: "BSIT401A",
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "4",
  },
  {
    id: "67",
    name: "BSIT401B",
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "4",
  },
  {
    id: "68",
    name: "BSIT401C",
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "4",
  },
];

export function getSectionStore() {
  return sections;
}
