import { ISubject } from "@/types/index";

const subjects: ISubject[] = [
  // Junior Highschool Grade Levels
  {
    _id: "1",
    code: "MAPEH7",
    title: "Music, Arts, PE & Health",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "2",
    code: "HR7",
    title: "Homeroom",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "3",
    code: "VE7",
    title: "Values Education",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "4",
    code: "TLE7",
    title: "Tech and Livelihood Educ",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "5",
    code: "Eng7",
    title: "English",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "6",
    code: "Math7",
    title: "Mathematics",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "7",
    code: "Sci7",
    title: "Science",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "8",
    code: "Fil7",
    title: "Filipino",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "9",
    code: "AP7",
    title: "Araling Panlipunan",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "10",
    code: "SOC7",
    title: "Student Organizations & Clubs",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "1",
    semester: "1st Semester",
  },

  // Grade 8
  {
    _id: "11",
    code: "MAPEH8",
    title: "Music, Arts, PE & Health",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "12",
    code: "HR8",
    title: "Homeroom",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "13",
    code: "TLE8",
    title: "Tech and Livelihood Educ",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "14",
    code: "VE8",
    title: "Values Education",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "15",
    code: "Math8",
    title: "Mathematics",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "16",
    code: "Eng8",
    title: "English",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "17",
    code: "Fil8",
    title: "Filipino",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "18",
    code: "Sci8",
    title: "Science",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "19",
    code: "AP8",
    title: "Araling Panlipunan",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "20",
    code: "SOC8",
    title: "Student Organizations & Clubs",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "2",
    semester: "1st Semester",
  },

  // Grade 9
  {
    _id: "21",
    code: "MAPEH9",
    title: "Music, Arts, PE & Health",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "22",
    code: "Sci9",
    title: "Science",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "23",
    code: "HR9",
    title: "Homeroom",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "24",
    code: "Eng9",
    title: "English",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "25",
    code: "AP9",
    title: "Araling Panlipunan",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "26",
    code: "Math9",
    title: "Mathematics",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "27",
    code: "Fil9",
    title: "Filipino",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "28",
    code: "TLE9",
    title: "Tech and Livelihood Educ",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "29",
    code: "ESP9",
    title: "Edukasyon sa Pagpapakatao",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "30",
    code: "Com9",
    title: "Computer",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "31",
    code: "SOC9",
    title: "Student Organizations & Clubs",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "3",
    semester: "1st Semester",
  },

  // Grade 10
  {
    _id: "32",
    code: "MAPEH10",
    title: "Music, Arts, PE & Health",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "33",
    code: "HR10",
    title: "Homeroom",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "34",
    code: "Math10",
    title: "Mathematics",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "35",
    code: "Eng10",
    title: "English",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "36",
    code: "AP10",
    title: "Araling Panlipunan",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "37",
    code: "Com10",
    title: "Computer",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "38",
    code: "ESP10",
    title: "Edukasyon sa Pagpapakatao",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "39",
    code: "TLE10",
    title: "Tech and Livelihood Educ",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "40",
    code: "Fil10",
    title: "Filipino",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "41",
    code: "Sci10",
    title: "Science",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "42",
    code: "SOC10",
    title: "Student Organizations & Clubs",
    type: "Lecture",
    units: 3,
    academicLevelId: "1",
    courseId: "1",
    yearLevelId: "4",
    semester: "1st Semester",
  },

  // Senior Highschool Grade Levels
  // ABM Grade 11
  {
    _id: "43",
    code: "SOC-G11-1st",
    title: "Student Org & Clubs",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "3",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "44",
    code: "MIL",
    title: "Media and Information Literacy",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "3",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "45",
    code: "ORG-MGT",
    title: "Organization & Management",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "3",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "46",
    code: "BUS-MATH",
    title: "Business Mathematics",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "3",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "47",
    code: "PHILO",
    title: "Intro to the Philo of Human",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "3",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "48",
    code: "PEH1",
    title: "Physical Education & Health 1",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "3",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "49",
    code: "ORAL-COM",
    title: "Oral Communication",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "3",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "50",
    code: "GEN-MATH",
    title: "General Mathematics",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "3",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "51",
    code: "21st-LIT",
    title: "21st Century Literature",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "3",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "52",
    code: "HR-G11-1st",
    title: "Homeroom",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "3",
    yearLevelId: "1",
    semester: "1st Semester",
  },

  // ABM Grade 12
  {
    _id: "53",
    code: "SOC-G12-1st",
    title: "Student Org & Clubs",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "3",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "54",
    code: "PERS-DEV",
    title: "Personal Development",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "3",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "55",
    code: "PRAC-RES2",
    title: "Practical Research 2",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "3",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "56",
    code: "PAGBASA",
    title: "Pagbasa at Pagsusuri",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "3",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "57",
    code: "PHYS-SCI",
    title: "Physical Science",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "3",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "58",
    code: "PEH3",
    title: "Physical Education & Health 3",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "3",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "59",
    code: "Eng-Prof",
    title: "English for Academic & Prof",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "3",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "60",
    code: "BUS-FIN",
    title: "Business Finance",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "3",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "61",
    code: "FBA-BM2",
    title: "Funda of Accountancy, BM 2",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "3",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "62",
    code: "HR-G12-1st",
    title: "Homeroom",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "3",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "63",
    code: "FIL-LARANG",
    title: "Fil sa Piling Larang (Akad)",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "3",
    yearLevelId: "2",
    semester: "1st Semester",
  },

  // HUMSS Grade 11
  {
    _id: "64",
    code: "SOC-G11-1st",
    title: "Student Org & Clubs",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "4",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "65",
    code: "21st-LIT",
    title: "21st Century Literature",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "4",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "66",
    code: "MIL",
    title: "Media and Information Literacy",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "4",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "67",
    code: "GEN-MATH",
    title: "General Mathematics",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "4",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "68",
    code: "WORLD-REL",
    title: "Intro to World Rel & BS",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "4",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "69",
    code: "PHILO",
    title: "Intro to the Philo of Human",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "4",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "70",
    code: "SS-DISS",
    title: "Disciplines & Ideas in the SS",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "4",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "71",
    code: "ORAL-COM",
    title: "Oral Communication",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "4",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "72",
    code: "HR-G11-1st",
    title: "Homeroom",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "4",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "73",
    code: "PEH1",
    title: "Physical Education & Health 1",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "4",
    yearLevelId: "1",
    semester: "1st Semester",
  },

  // HUMSS Grade 12
  {
    _id: "74",
    code: "SOC-G12-1st",
    title: "Student Org & Clubs",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "4",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "75",
    code: "PEH3",
    title: "Physical Education & Health 3",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "4",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "76",
    code: "FIL-LARANG",
    title: "Fil sa Piling Larang (Akad)",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "4",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "77",
    code: "PRAC-RES2",
    title: "Practical Research 2",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "4",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "78",
    code: "PERS-DEV",
    title: "Personal Development",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "4",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "79",
    code: "PHIL-POL",
    title: "Philippine Politics & Gov",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "4",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "80",
    code: "PAGBASA",
    title: "Pagbasa at Pagsusuri",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "4",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "81",
    code: "CRE-NON",
    title: "Creative Nonfiction",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "4",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "82",
    code: "Eng-Prof",
    title: "English for Academic & Prof",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "4",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "83",
    code: "HR-G12-1st",
    title: "Homeroom",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "4",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "84",
    code: "PHYS-SCI",
    title: "Physical Science",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "4",
    yearLevelId: "2",
    semester: "1st Semester",
  },

  // ITMAWD Grade 11
  {
    _id: "85",
    code: "SOC-G11-1st",
    title: "Student Org & Clubs",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "5",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "86",
    code: "GEN-MATH",
    title: "General Mathematics",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "5",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "87",
    code: "PEH1",
    title: "Physical Education & Health 1",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "5",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "88",
    code: "MIL",
    title: "Media and Information Literacy",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "5",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "89",
    code: "21st-LIT",
    title: "21st Century Literature",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "5",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "90",
    code: "ORAL-COM",
    title: "Oral Communication",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "5",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "91",
    code: "HR-G11-1st",
    title: "Homeroom",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "5",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "92",
    code: "PHILO",
    title: "Intro to the Philo of Human",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "5",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "93",
    code: "CP-WEB-PROG2",
    title: "Computer/Web Programming 2",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "5",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "94",
    code: "CP-WEB-PROG1",
    title: "Computer/Web Programming 1",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "5",
    yearLevelId: "1",
    semester: "1st Semester",
  },

  // ITMAWD Grade 12
  {
    _id: "95",
    code: "SOC-G12-1st",
    title: "Student Org & Clubs",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "5",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "96",
    code: "CP-WEB-PROG4",
    title: "Computer/Web Programming 4",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "5",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "97",
    code: "CP-WEB-PROG5",
    title: "Computer/Web Programming 5",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "5",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "98",
    code: "Eng-Prof",
    title: "English for Academic & Prof",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "5",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "99",
    code: "PAGBASA",
    title: "Pagbasa at Pagsusuri",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "5",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "100",
    code: "PHYS-SCI",
    title: "Physical Science",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "5",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "101",
    code: "FIL-LARANG-T",
    title: "Fil sa Piling Larang (Tech)",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "5",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "102",
    code: "PERS-DEV",
    title: "Personal Development",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "5",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "103",
    code: "HR-G12-1st",
    title: "Homeroom",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "5",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "104",
    code: "PRAC-RES2",
    title: "Practical Research 2",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "5",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "105",
    code: "PEH3",
    title: "Physical Education & Health 3",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "5",
    yearLevelId: "2",
    semester: "1st Semester",
  },

  // STEM Grade 11
  {
    _id: "106",
    code: "SOC-G11-1st",
    title: "Student Org & Clubs",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "2",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "107",
    code: "PEH1",
    title: "Physical Education & Health 1",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "2",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "108",
    code: "ORAL-COM",
    title: "Oral Communication",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "2",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "109",
    code: "21st-LIT",
    title: "21st Century Literature",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "2",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "110",
    code: "BIO1",
    title: "General Biology 1",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "2",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "111",
    code: "PHILO",
    title: "Intro to the Philo of Human",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "2",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "112",
    code: "GEN-MATH",
    title: "General Mathematics",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "2",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "113",
    code: "MIL",
    title: "Media and Information Literacy",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "2",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "114",
    code: "PRE-CAL",
    title: "Pre-Calculus",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "2",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "115",
    code: "HR-G11-1st",
    title: "Homeroom",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "2",
    yearLevelId: "1",
    semester: "1st Semester",
  },

  // STEM Grade 12
  {
    _id: "116",
    code: "SOC-G12-1st",
    title: "Student Org & Clubs",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "2",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "117",
    code: "CHEM1",
    title: "General Chemistry 1",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "2",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "118",
    code: "PRAC-RES2",
    title: "Practical Research 2",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "2",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "119",
    code: "PERS-DEV",
    title: "Personal Development",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "2",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "120",
    code: "Eng-Prof",
    title: "English for Academic & Prof",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "2",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "121",
    code: "PEH3",
    title: "Physical Education & Health 3",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "2",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "122",
    code: "PAGBASA",
    title: "Pagbasa at Pagsusuri",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "2",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "123",
    code: "DRRR",
    title: "Disaster Readiness & Risk Redu",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "2",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "124",
    code: "FIL-LARANG",
    title: "Fil sa Piling Larang (Akad)",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "2",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "125",
    code: "HR-G12-1st",
    title: "Homeroom",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "2",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "126",
    code: "PHYSICS1",
    title: "General Physics 1",
    type: "Lecture",
    units: 3,
    academicLevelId: "2",
    courseId: "2",
    yearLevelId: "2",
    semester: "1st Semester",
  },

  // Tertiary Grade Levels
  // BSAIS 1st year
  {
    _id: "127",
    code: "CONTEMP",
    title: "The Contemporary World",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "128",
    code: "NSTP1",
    title: "NSTP 1",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "129",
    code: "PHIL-HIST",
    title: "Readings in Philippine History",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "130",
    code: "UTS",
    title: "Understanding the Self",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "131",
    code: "STS",
    title: "Science, Technology, & Society",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "132",
    code: "POP-CULT",
    title: "Philippine Popular Culture",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "133",
    code: "BASIC-ACC",
    title: "Basic Accounting",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "134",
    code: "EUTH1",
    title: "Euthenics 1",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "135",
    code: "PATHFIT1",
    title: "P.E./PATHFIT 1: (MCT)",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "1",
    semester: "1st Semester",
  },

  // BSAIS 2nd year
  {
    _id: "136",
    code: "PATHFIT3",
    title: "P.E./PATHFIT 3: (I & DS)",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "137",
    code: "STRAT-MGT",
    title: "Strategic Management",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "138",
    code: "GREAT-BKS",
    title: "Great Books",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "139",
    code: "BUS-LAW",
    title: "Business Laws and Regulations",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "140",
    code: "PURP-COMM",
    title: "Purposive Communication",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "141",
    code: "RIZAL",
    title: "Rizal's Life and Works",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "142",
    code: "INT-ACC1",
    title: "Intermediate Accounting 1",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "143",
    code: "INT-ACC1-LAB",
    title: "Intermediate Accounting 1",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "144",
    code: "IT-TOOLS",
    title: "IT App Tools in Business",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "145",
    code: "IT-TOOLS-LAB",
    title: "IT App Tools in Business",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "146",
    code: "MGR-ECO",
    title: "Managerial Economics",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "2",
    semester: "1st Semester",
  },

  // BSAIS 3rd year
  {
    _id: "147",
    code: "ECON-DEV",
    title: "Economic Development",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "148",
    code: "GOV",
    title: "Governance, Bus Ethic, RM & IC",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "149",
    code: "INT-BUSI",
    title: "International Business & Trade",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "150",
    code: "ISAD",
    title: "Info Sys Analysis & Design",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "151",
    code: "ISAD-LAB",
    title: "Info Sys Analysis & Design",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "152",
    code: "INT-ACC3",
    title: "Intermediate Accounting 3",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "153",
    code: "INT-ACC3-LAB",
    title: "Intermediate Accounting 3",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "154",
    code: "COST-ACC",
    title: "Cost Accounting and Control",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "155",
    code: "FIN-MKT",
    title: "Financial Markets",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "156",
    code: "STAT-APP",
    title: "Stat Analysis w/ Soft App",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "157",
    code: "STAT-APP-LAB",
    title: "Stat Analysis w/ Soft App",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "3",
    semester: "1st Semester",
  },

  // BSAIS 4th year
  {
    _id: "158",
    code: "BUSI-ANALYTICS",
    title: "Business Analytics",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "159",
    code: "HRM",
    title: "Human Resource Management",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "160",
    code: "MGT-SCI",
    title: "Management Science",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "161",
    code: "EUTH2",
    title: "Euthenics 2",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "162",
    code: "INFO-SEC",
    title: "Information Security & Mgt",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "163",
    code: "INFO-SEC-LAB",
    title: "Information Security & Mgt",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "164",
    code: "STRAT-BUSI",
    title: "Strategic Business Analysis",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "165",
    code: "MGT-REPORT",
    title: "Management Reporting",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "166",
    code: "FIN-MODEL",
    title: "Financial Modeling",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "6",
    yearLevelId: "4",
    semester: "1st Semester",
  },

  // BSBA 1st year
  {
    _id: "167",
    code: "MICRO",
    title: "Basic Microeconomics",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "168",
    code: "NSTP1",
    title: "NSTP 1",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "169",
    code: "PHIL-HIST",
    title: "Readings in Philippine History",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "170",
    code: "EUTH1",
    title: "Euthenics 1",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "171",
    code: "CONTEMP",
    title: "The Contemporary World",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "172",
    code: "UTS",
    title: "Understanding the Self",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "173",
    code: "PATHFIT1",
    title: "P.E./PATHFIT 1: (MCT)",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "1",
    semester: "1st Semester",
  },

  // BSBA 2nd year
  {
    _id: "174",
    code: "PATHFIT3",
    title: "P.E./PATHFIT 3: (I & DS)",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "175",
    code: "FACIL-MGT",
    title: "Facilities Management",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "176",
    code: "COSTING",
    title: "Costing and Pricing",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "177",
    code: "COSTING-LAB",
    title: "Costing and Pricing",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "178",
    code: "PURP-COMM",
    title: "Purposive Communication",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "179",
    code: "POP-CULT",
    title: "Philippine Popular Culture",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "180",
    code: "RIZAL",
    title: "Rizal's Life and Works",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "2",
    semester: "1st Semester",
  },

  // BSBA 3rd year
  {
    _id: "181",
    code: "INT-BUSI",
    title: "International Business & Trade",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "182",
    code: "GOV-SOC",
    title: "Good Governance & Social Resp",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "183",
    code: "GREAT-BKS",
    title: "Great Books",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "184",
    code: "OPS-MGT",
    title: "Operations Management (TQM)",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "185",
    code: "BUSI-RES",
    title: "Business Research",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "186",
    code: "MGR-ACC",
    title: "Managerial Accounting",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "187",
    code: "MGR-ACC-LAB",
    title: "Managerial Accounting",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "3",
    semester: "1st Semester",
  },

  // BSBA 4th year
  {
    _id: "188",
    code: "EUTH2",
    title: "Euthenics 2",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "189",
    code: "ENT-MGT",
    title: "Entrepreneurial Management",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "190",
    code: "MKT-MGT",
    title: "Marketing Management",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "191",
    code: "SPEC-TOPIC",
    title: "Special Topics in Oper Mgt",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "192",
    code: "FIN-MGT",
    title: "Financial Management",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "193",
    code: "FEAS-STUDY",
    title: "Feasibility Study",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "7",
    yearLevelId: "4",
    semester: "1st Semester",
  },

  // BSCPE 1st year
  {
    _id: "194",
    code: "CONTEMP",
    title: "The Contemporary World",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "195",
    code: "NSTP1",
    title: "NSTP 1",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "196",
    code: "MATH-MOD",
    title: "Math in the Modern World",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "197",
    code: "PROG-LOGIC",
    title: "Programming Logic and Design",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "198",
    code: "PROG-LOGIC-LAB",
    title: "Programming Logic and Design",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "199",
    code: "COL-CALC",
    title: "College Calc (Differential)",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "200",
    code: "UTS",
    title: "Understanding the Self",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "201",
    code: "EUTH1",
    title: "Euthenics 1",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "202",
    code: "PATHFIT1",
    title: "P.E./PATHFIT 1: (MCT)",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "203",
    code: "CPE-DISC",
    title: "Computer Engg as a Discipline",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "204",
    code: "CHEM-ENG",
    title: "Chemistry for Engineers",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "1",
    semester: "1st Semester",
  },

  // BSCPE 2nd year
  {
    _id: "205",
    code: "ENT-MIND",
    title: "The Entrepreneurial Mind",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "206",
    code: "PHIL-HIST",
    title: "Readings in Philippine History",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "207",
    code: "DATA-STRUCT",
    title: "Data Structures and Algorithms",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "208",
    code: "DATA-STRUCT-LAB",
    title: "Data Structures and Algorithms",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "209",
    code: "ELEC-CIRC",
    title: "Fundamentals of Elec Circ",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "210",
    code: "ELEC-CIRC-LAB",
    title: "Fundamentals of Elec Circ",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "211",
    code: "RIZAL",
    title: "Rizal's Life and Works",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "212",
    code: "PATHFIT3",
    title: "P.E./PATHFIT 3: (I & DS)",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "213",
    code: "EMER-TECH",
    title: "Emerging Technologies in CpE",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "214",
    code: "EMER-TECH-LAB",
    title: "Emerging Technologies in CpE",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "215",
    code: "DIFF-EQ",
    title: "Differential Equations",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "216",
    code: "OS",
    title: "Operating Systems",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "2",
    semester: "1st Semester",
  },

  // BSCPE 3rd year
  {
    _id: "217",
    code: "LOGIC-CIRC",
    title: "Logic Circuits and Design",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "218",
    code: "LOGIC-CIRC-LAB",
    title: "Logic Circuits and Design",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "219",
    code: "ENG-ECON",
    title: "Engineering Economics",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "220",
    code: "FEED-CONTROL",
    title: "Feedback and Control Systems",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "221",
    code: "COMP-ARCH",
    title: "Computer Systems Architecture",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "222",
    code: "COMP-ARCH-LAB",
    title: "Computer Systems Architecture",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "223",
    code: "CAD",
    title: "Computer-Aided Drafting",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "224",
    code: "CAD-LAB",
    title: "Computer-Aided Drafting",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "225",
    code: "DATA-COMM",
    title: "Data & Digital Comm (Data Com)",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "226",
    code: "CPE-DRAFT",
    title: "Computer Engg Drafting & Des",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "227",
    code: "CPE-DRAFT-LAB",
    title: "Computer Engg Drafting & Des",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "228",
    code: "RES-METH",
    title: "Methods of Research",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "229",
    code: "MIXED-SIG",
    title: "Funda of Mixed Signals & Sens",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "230",
    code: "MIXED-SIG-LAB",
    title: "Funda of Mixed Signals & Sens",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "3",
    semester: "1st Semester",
  },

  // BSCPE 4th year
  {
    _id: "231",
    code: "ROBOT-ASS",
    title: "Robot Assembly and Programming",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "232",
    code: "ROBOT-ASS-LAB",
    title: "Robot Assembly and Programming",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "233",
    code: "CPE-LAW",
    title: "CpE Laws & Profnl Practice",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "234",
    code: "NET-SEC",
    title: "Computer Network and Security",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "235",
    code: "NET-SEC-LAB",
    title: "Computer Network and Security",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "236",
    code: "EUTH2",
    title: "Euthenics 2",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "237",
    code: "CAPSTONE2",
    title: "Capstone Design 2",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "238",
    code: "COMP-ORG",
    title: "Computer Architecture and Org",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "239",
    code: "COMP-ORG-LAB",
    title: "Computer Architecture and Org",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "240",
    code: "EMBEDDED",
    title: "Embedded Systems",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "241",
    code: "EMBEDDED-LAB",
    title: "Embedded Systems",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "242",
    code: "SEMINARS",
    title: "Seminars and Fieldtrips",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "8",
    yearLevelId: "4",
    semester: "1st Semester",
  },

  // BSHM 1st year
  {
    _id: "243",
    code: "PHIL-HIST",
    title: "Readings in Philippine History",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "244",
    code: "UTS",
    title: "Understanding the Self",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "245",
    code: "MACRO-TH",
    title: "Macro Prspctv of Toursm & Hosp",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "246",
    code: "NSTP1",
    title: "NSTP 1",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "247",
    code: "RISK-MGT",
    title: "Risk Mgt as Applied to SSS",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "248",
    code: "MATH-MOD",
    title: "Math in the Modern World",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "249",
    code: "EUTH1",
    title: "Euthenics 1",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "250",
    code: "PATHFIT1",
    title: "P.E./PATHFIT 1: (MCT)",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "1",
    semester: "1st Semester",
  },

  // BSHM 2nd year
  {
    _id: "251",
    code: "FOR-LANG1",
    title: "Foreign Language 1",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "252",
    code: "PHIL-CUIS",
    title: "Phil Reg Cuis w/ Food SD",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "253",
    code: "PHIL-CUIS-LAB",
    title: "Phil Reg Cuis w/ Food SD",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "254",
    code: "HOTEL-FRONT",
    title: "Hotel Front Ofc Operations Mgt",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "255",
    code: "ART-APP",
    title: "Art Appreciation",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "256",
    code: "QUAL-SERV",
    title: "Quality Serv Mgt Tour & Hosp",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "257",
    code: "PATHFIT3",
    title: "P.E./PATHFIT 3: (I & DS)",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "258",
    code: "LODGING-OPS",
    title: "Fundamentals in Lodging Oper",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "259",
    code: "LODGING-OPS-LAB",
    title: "Fundamentals in Lodging Oper",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "2",
    semester: "1st Semester",
  },

  // BSHM 3rd year
  {
    _id: "260",
    code: "OPS-MGT",
    title: "Operations Management (TQM)",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "261",
    code: "MULT-DIV",
    title: "Multicultural Diversity in WTP",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "262",
    code: "GREAT-BKS",
    title: "Great Books",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "263",
    code: "PROF-DEV",
    title: "Profe Dev & Applied Ethics",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "264",
    code: "TH-MKTG",
    title: "Tourism & Hospitality Mrktg",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "265",
    code: "ENT-MIND",
    title: "The Entrepreneurial Mind",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "266",
    code: "PASTRY-ARTS",
    title: "Pastry Arts and Bakery Mgt",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "267",
    code: "PASTRY-ARTS-LAB",
    title: "Pastry Arts and Bakery Mgt",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "268",
    code: "BUSI-TOOLS",
    title: "Applied Busi Tools & Tech Hosp",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "269",
    code: "BUSI-TOOLS-LAB",
    title: "Applied Busi Tools & Tech Hosp",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "3",
    semester: "1st Semester",
  },

  // BSHM 4th year
  {
    _id: "270",
    code: "EUTH2",
    title: "Euthenics 2",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "271",
    code: "SPEC-CUIS",
    title: "Specialty Cuisine w/ Food Exh",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "272",
    code: "SPEC-CUIS-LAB",
    title: "Specialty Cuisine w/ Food Exh",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "273",
    code: "CONTEMP",
    title: "The Contemporary World",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "274",
    code: "HOSP-RES",
    title: "Research in Hospitality",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "275",
    code: "RIZAL",
    title: "Rizal's Life and Works",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "9",
    yearLevelId: "4",
    semester: "1st Semester",
  },

  // BSIT 1st year
  {
    _id: "276",
    code: "EUTH1",
    title: "Euthenics 1",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "277",
    code: "POP-CULT",
    title: "Philippine Popular Culture",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "278",
    code: "UTS",
    title: "Understanding the Self",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "279",
    code: "NSTP1",
    title: "NSTP 1",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "280",
    code: "PURP-COMM",
    title: "Purposive Communication",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "281",
    code: "INTRO-COMP",
    title: "Introduction to Computing",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "282",
    code: "INTRO-COMP-LAB",
    title: "Introduction to Computing",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "283",
    code: "COMP-PROG1",
    title: "Computer Programming 1",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "284",
    code: "COMP-PROG1-LAB",
    title: "Computer Programming 1",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "285",
    code: "PATHFIT1",
    title: "P.E./PATHFIT 1: (MCT)",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "1",
    semester: "1st Semester",
  },
  {
    _id: "286",
    code: "CONTEMP",
    title: "The Contemporary World",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "1",
    semester: "1st Semester",
  },

  // BSIT 2nd year
  {
    _id: "287",
    code: "PATHFIT3",
    title: "P.E./PATHFIT 3: (I & DS)",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "288",
    code: "OOP",
    title: "Object-Oriented Programming",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "289",
    code: "OOP-LAB",
    title: "Object-Oriented Programming",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "290",
    code: "PLAT-TECH",
    title: "Platform Technology (OS)",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "291",
    code: "PLAT-TECH-LAB",
    title: "Platform Technology (OS)",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "292",
    code: "HCI",
    title: "Human-Computer Interaction",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "293",
    code: "HCI-LAB",
    title: "Human-Computer Interaction",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "294",
    code: "PHIL-HIST",
    title: "Readings in Philippine History",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "295",
    code: "RIZAL",
    title: "Rizal's Life and Works",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "296",
    code: "DATA-STRUCT",
    title: "Data Structures and Algorithms",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "297",
    code: "DATA-STRUCT-LAB",
    title: "Data Structures and Algorithms",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "2",
    semester: "1st Semester",
  },
  {
    _id: "298",
    code: "COMM-PRIN",
    title: "Principles of Communication",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "2",
    semester: "1st Semester",
  },

  // BSIT 3rd year
  {
    _id: "299",
    code: "ADV-DB",
    title: "Advanced Database Systems",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "300",
    code: "ADV-DB-LAB",
    title: "Advanced Database Systems",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "301",
    code: "ENT-ARCH",
    title: "Enterprise Architecture",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "302",
    code: "ENT-ARCH-LAB",
    title: "Enterprise Architecture",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "303",
    code: "PROB-ISS",
    title: "Prof Issues in Info Sys & Tech",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "304",
    code: "ADV-SYS",
    title: "Advance Sys Integration & Arch",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "305",
    code: "ADV-SYS-LAB",
    title: "Advance Sys Integration & Arch",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "306",
    code: "DATA-COMM",
    title: "Data & Digital Comm (Data Com)",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "307",
    code: "APP-DEV",
    title: "App Dev & Emerging Tech",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "308",
    code: "APP-DEV-LAB",
    title: "App Dev & Emerging Tech",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "309",
    code: "EVENT-PROG",
    title: "Event-Driven Programming",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "3",
    semester: "1st Semester",
  },
  {
    _id: "310",
    code: "EVENT-PROG-LAB",
    title: "Event-Driven Programming",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "3",
    semester: "1st Semester",
  },

  // BSIT 4th year
  {
    _id: "311",
    code: "GAME-DEV",
    title: "Game Development",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "312",
    code: "GAME-DEV-LAB",
    title: "Game Development",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "313",
    code: "CAPSTONE2",
    title: "IT Capstone Project 2",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "314",
    code: "EUTH2",
    title: "Euthenics 2",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "315",
    code: "NET-TECH2",
    title: "Network Technology 2",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "316",
    code: "NET-TECH2-LAB",
    title: "Network Technology 2",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "317",
    code: "INFO-SEC",
    title: "Info Assurance & Sec (DP)",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "318",
    code: "INFO-SEC-LAB",
    title: "Info Assurance & Sec (DP)",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "319",
    code: "COMP-GRAPH",
    title: "Computer Graphics Programming",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "320",
    code: "COMP-GRAPH-LAB",
    title: "Computer Graphics Programming",
    type: "Laboratory",
    units: 1,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "4",
    semester: "1st Semester",
  },
  {
    _id: "321",
    code: "IT-SVC",
    title: "IT Service Management",
    type: "Lecture",
    units: 3,
    academicLevelId: "3",
    courseId: "10",
    yearLevelId: "4",
    semester: "1st Semester",
  },
];

export function getSubjectStore() {
  return subjects;
}
